QuickfitApp/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using DataLayer;
using LogicLayer;
using System.Web;


namespace QuickfitApp.Controllers
{
    public class ExerciseController : Controller
    {
        ExerciseContainer exerciseContainer = new ExerciseContainer(AppSettingsJson.GetConnectionstring());
        Exercise exercise = new Exercise(AppSettingsJson.GetConnectionstring());
        public ActionResult Index()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index","Home");
            }
            List<ExerciseModel> exercises = exerciseContainer.GetAll(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            return View(exercises);
        }

        [HttpPost]
        public ActionResult Index(string sortField)
        {
            try
            {
                sortField = Request.Form["orderString"];
                List<ExerciseModel> exercises = exerciseContainer.GetAll(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")), sortField);
                return View(exercises);
            }
            catch
            {
                return RedirectToAction("Index","Account");
            }
        }

        public ActionResult Edit(int id)
        {
            var exercise = exerciseContainer.FindById(id);
            return View(exercise);
        }

        [HttpPost]
        public ActionResult Edit(ExerciseModel exerciseModel)
        {
            try
            {
                exercise.UpdateExercise(exerciseModel.Id, exerciseModel.Name, exerciseModel.Weight, exerciseModel.Repetitions, exerciseModel.Level);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Level", "Something was not filled in correctly, try again!");
                return View(exerciseModel);
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ExerciseModel exercise)
        {

            if (ModelState.IsValid)
            {
                exerciseContainer.Add(exercise, Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
                exercise.InWorkout = false;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Level", "Something was not filled in correctly, try again!");
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            ExerciseModel exerciseModel = exerciseContainer.FindById(id);
            return View(exerciseModel);
        }

        [HttpPost]
        public ActionResult Delete(ExerciseModel exerciseModel)
        {
            try
            {
                exerciseContainer.Delete(exerciseModel.Id);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Level", "Something went wrong, try again!");
                return View(exerciseModel);
            }
        }
    }
}

QuickfitApp/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Models;
using Microsoft.AspNetCore.Http;
using LogicLayer;
namespace QuickfitApp.Controllers
{
    public class WorkoutController : Controller
    {
        Workout workout = new Workout(AppSettingsJson.GetConnectionstring());
        WorkoutContainer workoutContainer = new WorkoutContainer(AppSettingsJson.GetConnectionstring());
        ExerciseContainer exerciseContainer = new ExerciseContainer(AppSettingsJson.GetConnectionstring());
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<WorkoutModel> workoutlist = workoutContainer.GetAll(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            return View(workoutlist);
        }

        public ActionResult Delete(int id)
        {
            var workout = workoutContainer.FindById(id);
            return View(workout);
        }

        [HttpPost]
        public ActionResult Delete(WorkoutModel workout)
        {
            try
            {
                workoutContainer.Delete(workout.Id);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Category", "Something went wrong, try again!");
                return View(workout);
            }
        }

        public ActionResult Edit(int id)
        {
            var workout = workoutContainer.FindById(id);
            return View(workout);
        }

        [HttpPost]
        public ActionResult Edit(int id, string name, string skillevel, int time, string category)
        {
            try
            {
                workout.UpdateWorkout(id, name, skillevel, time, category);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Gender", "Something was not filled in correctly, try again!");
                return View(workoutContainer.FindById(id));
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(WorkoutModel workout)
        {
            if (ModelState.IsValid)
            {
                workoutContainer.Add(workout, Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Category", "Something was not filled in correctly, try again!");
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var workout = workoutContainer.FindById(id);
            TempData["WorkoutId"] = id;
            workout.Exercises = workoutContainer.GetExercisesInWorkout(id);
            return View(workout);
        }

        public ActionResult AddExerciseToWorkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddExerciseToWorkout(ExerciseModel exercise)
        {
            if (ModelState.IsValid)
            {
                int userId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                exercise.InWorkout = true;
                int workoutId = Convert.ToInt32(TempData["WorkoutId"]);
                workoutContainer.AddExerciseToWorkout(userId, exercise, workoutId);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Gender", "Something was not filled in correctly, try again!");
                return View();
            }
        }

    }
}

QuickfitApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuickfitApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Index">QuickfitApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="Index">Exercises</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Index">Workouts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container containerWrapper">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - QuickfitApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

QuickfitApp/Views/Shared/_LayoutBeforeLoggedIn.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuickfitApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Index">QuickfitApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                </div>
            </div>
        </nav>
    </header>
    <div class="container containerWrapper">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - QuickfitApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>